### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by jmaczura** [endoit/vscode-siebelscriptseditor#1]
Hello!  

I have a local 19c DB instance running that I use with Siebel 22.5.  I installed the 64-bit Oracle instant client from the link provided, and created tnsnames.ora with the same entry as my 32-bit Oracle client, added the instantclient directory to PATH, and downloaded the latest redistributable.  I installed that and restarted my PC.

Clicking Test Database connection shows the error "Error connecting to database: ORA-12521: TNS:listener does not currently know of instance requested in connect descriptor".  It looks like there may be an issue with the 64-bit Oracle Client, but I'm not sure what else to do.

My full DB Connection string is:
LocalDev/SADMIN/_sadminpassword_@localhost:1521/orcl.lan/SADMIN

Any advice is appreciated.

**Comment by kishorev6** [comment]
Hi jmaczura,

I did the same as yours(i use 19c) my error says "Error connecting to database: ORA-00942: table or view does not exist"

Thanks,
Venkat

**Comment by lbakosendo** [comment]
Hi @jmaczura,

The Siebel username should be preceded by an "@", not a "/", in your example: LocalDev/SADMIN/sadminpassword@localhost:1521/orcl.lan@SADMIN

If you use "/", then the error given is the one you have encountered. Please check if this fixes your issue.

Hi @kishorev6,

Could you please elaborate when did you get this error? After clicking the "Test database connection" button? That button sends the following query to the database: SELECT ROW_ID, NAME FROM SIEBEL.S_REPOSITORY.

Thank you for your feedback,
László

**Comment by kishorev6** [comment]
@istikradendoit  Thanks for the response, attached detailed document.


Thanks,
Venkat
[Script editor.docx](https://github.com/endoit/vscode-siebelscriptseditor/files/8853613/Script.editor.docx)

**Comment by jmaczura** [comment]
Thank you so much, László.  I successfully connected.
